; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Sep 28 2020 11:43:04 GMT+0200 (Central European Summer Time)
M280 P0 S10 ; deploy BLTouch

