; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Mon Sep 28 2020 11:43:04 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0
M703
